### ISSUE TITLE
Handling dead objects

### ISSUE THREAD

**Issue by asleep-cult** [asleep-cult/snekcord#52]
When processing data from Discord's API, it is a very common occurrence to receive partial objects that the client can't see. These objects will stay in cache forever because of the simple fact that the client doesn't receive gateway events for them. This constant cache growth could quickly become an issue. Here are a few of the solutions I've considered:

1. Trash the object and expose the object's ID
2. Create a different class for the partial objects which never gets cached
3. Perform an `upsert` but with don't cache newly created objects
4. Perform an `upsert` but cache newly created objects in a `WeakValueDictionary` and move them to the regular cache after an update from the gateway

@ToxicKidz hello

**Comment by ToxicKidz** [comment]
I like the fourth option

**Comment by asleep-cult** [comment]
> I like the fourth option

OK, I'm going to try and define a few things.
There are 2 different types of states: bound and unbound states. Bound states are directly tied to another object and will receive their data from that object (bound states don't include sub-states). Unbound states are states that could be tied to another object but don't receive their data from that object... ever.

The currently existing bound states are:
* `PermissionOverwriteState`
* `ReactionsState`
* `RoleState`

The currently existing unbound states are:
* `GuildState`
* `GuildBanState`
* `IntegrationState`
* `InviteState`
* `GuildMemberState`
* `MessageState`
* `UserState`

The weird states (not tied to objects but receive their data from them) are
* `ChannelState`
* `EmojiState`
* `StickerState`
* `StageInstanceState`

So what's the need for this distinction? Unbound states can have partial data, bound states can't and thus their objects only die when their owner dies.

What do unbound states need to have?
* A weak mapping for newly created objects
* A mapping for objects that are definitely not dead to the client
* A method for promoting objects to the second mapping

Why am I writing this? i forgor :skull: 

Edit: `ChannelState` is in the weird category

**Comment by asleep-cult** [comment]
So I started working on an implementation and I've decided that number 4 is just too complicated. Do you think a simple "garbage collector" would suffice?
