### ISSUE TITLE
Asyncio bad scarletio good

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [asleep-cult/snekcord#78]
Ayaya

**Comment by zeffo** [comment]
ratio

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Scarletio is faster tho lul

**Comment by zeffo** [comment]
Proof?

**Comment by ToxicKidz** [comment]
Source: Trust me bro

**Comment by HuyaneMatsu** [comment]
> Scarletio is faster tho lul

I approve this claim.

**Comment by ToxicKidz** [comment]
> > Scarletio is faster tho lul
> 
> I approve this claim.

I disapprove this claim.

**Comment by HuyaneMatsu** [comment]
> I disapprove this claim.

Source: Trust me bro
